name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Run database tests
      run: |
        cd packages/app
        pnpm run test:unit

  electron-tests:
    runs-on: ubuntu-latest
    name: Electron UI Tests

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Install Playwright browsers
      run: |
        cd packages/app
        npx playwright install --with-deps chromium

    - name: Run Electron Playwright tests
      timeout-minutes: 5
      run: |
        cd packages/app
        xvfb-run -a --server-args="-screen 0 1280x720x24" pnpm run test:e2e
      env:
        CI: true